version: "3.7"

networks:
  application-network:
    driver: bridge
    name: sber_network

services:
  application-api-nginx:
    restart: always
    container_name: application-api-nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - application-api-php
    ports:
      - "8000:80"
    volumes:
      - "./.:/app/"
    networks:
      - application-network

  application-api-php:
    restart: always
    container_name: application-api-php
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - application-api-postgres
    env_file:
      - ./.env
    volumes:
      - ".:/app"
    networks:
      - application-network

  application-api-postgres:
    restart: always
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    container_name: application-api-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - application-network
    env_file:
      - .env
    volumes:
      - "./.data/database/postgres/data:/var/lib/postgresql/data"

  application-api-redis:
    restart: always
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    container_name: application-api-redis
    volumes:
      - ./.data/storage/redis/redis-data:/var/lib/redis
      - ./.data/storage/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    env_file:
      - .env
    expose:
      - "6379"
    networks:
      - application-network

  application-api-rabbitmq:
    restart: always
    build:
      context: ./.docker/rabbitmq
      dockerfile: Dockerfile
    container_name: application-api-rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - application-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: application-api-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
